name: .NET
#env:
#      working-directory: Allfiles/Labs/04/Solution/AdventureWorks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#defaults:
#  run:
#    working-directory: ./your_working_dir

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: Allfiles/Labs/04/Solution/AdventureWorks

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Dir
      run: ls -hla
    - name: Dir2
      run: ls -hla
      working-directory: ${{env.working-directory}}
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
